### PR TITLE
Fix minor typo

### LINKED ISSUE #40: Typo in variable name "slo_forwad_on_logout"
In the README.md, it says:

> The SAMLAuthenticator usually attempts to forward users to the SLO URI set in the SAML Metadata. If this is not the desired behavior for whatever reason, set slo_forward_on_logout to False. This will change the page the user is forwarded to on logout from the page specified in the xml metadata to the standard jupyterhub logout page.

However, the example config in the README and the code itself uses the variable name "slo_forwad_on_logout".

### PR DESCRIPTION
**Pull request by duongnt**
Fix forwad -> forward (Fix #40)
```
Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 660 York Street, Suite 102, San Francisco, CA 94110 USA

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.
```

Signed-off-by: Thi Duong Nguyen

### CODE REVIEW

**Comment by distortedsignal** [comment]
I think this is a good start, but I'm a little concerned that we're breaking backward compatibility with this change. Someone out there who has `slo_forwad_on_logout` set might get broken by this. Is it ok if I make a PR against your branch?

**Comment by duongnt** [comment]
> I think this is a good start, but I'm a little concerned that we're breaking backward compatibility with this change. Someone out there who has `slo_forwad_on_logout` set might get broken by this. Is it ok if I make a PR against your branch?

Sure. I guess we can leave the typo `slo_forwad_on_logout` there for backward-compatibility, but add a [Deprecated] note?

**Comment by distortedsignal** [comment]
@duongnt If you merge my `distortedsignal:ds-minor-changed` branch into your branch, I'll merge your branch into this master and then cut a bugfix release.

**Comment by duongnt** [comment]
> @duongnt If you merge my `distortedsignal:ds-minor-changed` branch into your branch, I'll merge your branch into this master and then cut a bugfix release.

Thanks @distortedsignal, I merged your changes to my master.

**Comment by ebebpl** [comment]
Hello,
Thanks for awesome work! The SAMLAuthenticator is mostly working as documented. Ran into an issue when setting the c.SAMLAuthenticator.slo_forwad_on_logout = True . Tried both 'forward' and 'forwad'.
What should this value be set to?

[E 2020-03-16 18:36:36.179 JupyterHub web:1670] Uncaught exception GET /hub/logout (::ffff:10.x.x.x)
    HTTPServerRequest(protocol='http', host='myhost.com:8000', method='GET', uri='/hub/logout', version='HTTP/1.1', remote_ip='::ffff:10.x.x.x')
    Traceback (most recent call last):
      File "/datar10/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/anaconda3/lib/python3.7/site-packages/samlauthenticator/samlauthenticator.py", line 754, in get
        forwad_on_logout = True if authenticator_self.slo_forwad_on_logout else False
    AttributeError: 'SAMLAuthenticator' object has no attribute 'slo_forwad_on_logout'

**Pull request merged**
